{{- if .Values.adotCollector.sidecar.enabled }}
# ADOT Collector as a Sidecar for deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}
    {{- include "adotCollector.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.adotCollector.sidecar.replicas }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
        {{- include "adotCollector.labels" . | indent 8 }}
    spec:
      containers:
        - name: "{{ .Values.adotCollector.image.name }}"
          image: "{{ .Values.adotCollector.image.repository }}:{{ .Values.adotCollector.image.tag }}"
          imagePullPolicy: {{ .Values.adotCollector.image.pullPolicy }}
        - name: "{{ .Values.adotCollector.image.name }}"
          image: "{{ .Values.adotCollector.image.repository }}:{{ .Values.adotCollector.image.tag }}"
          env:
            - name: AWS_REGION
              value: {{ .Values.awsRegion }}
          imagePullPolicy: {{ .Values.adotCollector.image.sidecarPullPolicy }}
          resources:
            limits:
              cpu: "256m"
              memory: "512Mi"
            requests:
              cpu: "32m"
              memory: "24Mi"
                  {{- toYaml .Values.adotCollector.sidecar.resources | nindent 12 }}
      {{- end }}
